
CREATE OR REPLACE DATABASE tasks_db CHARACTER SET "utf8mb4";

USE tasks_db;

CREATE OR REPLACE TABLE users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL
);

CREATE OR REPLACE TABLE tasks (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    done BOOLEAN NOT NULL DEFAULT FALSE,
    uid INT UNSIGNED NOT NULL,
    CONSTRAINT FOREIGN KEY (uid) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE OR REPLACE TABLE refresh_tokens (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uid INT UNSIGNED NOT NULL,
    token_id UUID NOT NULL,
    delete_after DATETIME NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT FOREIGN KEY (uid) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE OR REPLACE EVENT refresh_token_cleanup
  ON SCHEDULE EVERY 5 MINUTE DO
    DELETE FROM refresh_tokens
    WHERE TO_SECONDS(delete_after) < TO_SECONDS(NOW());
