#!/bin/bash
set -euo pipefail

sudo apt-get --update install 7zip composer php-fpm php-mysql openssl -y

db_pass=$(openssl rand -base64 64)

sudo mariadb -u root -e "SOURCE /var/www/tasks/db.sql;CREATE OR REPLACE USER tasks IDENTIFIED BY \"$db_pass\";GRANT ALL ON tasks_db.* TO tasks;"

# Generate php config file
rm -f web_server/config.php
printf "<?php\n// This file is automatically generated\n\ndeclare(strict_types=1);\n\nclass Config\n{\n" | tee -a web_server/config.php > /dev/null
printf "    public static string \$database_hostname = \"database:3306\";\n" | tee -a web_server/config.php > /dev/null
printf "    public static string \$database_username = \"tasks\";\n" | tee -a web_server/config.php > /dev/null
printf "    public static string \$database_password = \"%s\";\n" "$db_pass" | tee -a web_server/config.php > /dev/null
printf "    public static string \$database_name = \"tasks_db\";\n" | tee -a web_server/config.php > /dev/null
printf "}\n" | tee -a web_server/config.php > /dev/null

openssl rand -out web_server/secret.key -base64 32
openssl req -x509 -nodes -days 730 -newkey rsa:2048 -keyout tasks.key -out tasks.pem -config san.cnf

cd web_server
composer require lcobucci/jwt lcobucci/clock ramsey/uuid
cd ..
