#!/bin/bash
set -euo pipefail

sudo apt-get --update full-upgrade
if ! command -v grep >/dev/null 2>&1
then sudo apt-get install grep
fi
if ! command -v composer >/dev/null 2>&1
then sudo apt-get install composer
fi
if ! command -v 7z >/dev/null 2>&1
then sudo apt-get install 7zip
fi
if ! command -v mariadb >/dev/null 2>&1
then sudo apt-get install mariadb-server
fi
if ! dpkg -l | grep php-mysql >/dev/null 2>&1
then sudo apt-get install php-mysql
fi
if ! command -v openssl >/dev/null 2>&1
then sudo apt-get install openssl
fi
if ! dpkg -l | grep nginx >/dev/null 2>&1
then sudo apt-get install nginx
fi
if ! dpkg -l | grep php-fpm >/dev/null 2>&1
then sudo apt-get install php-fpm
fi

db_pass=$(openssl rand -base64 256)
sudo mariadb -u root -e "source db.sql;CREATE OR REPLACE USER tasks IDENTIFIED BY \"$db_pass\";GRANT ALL ON tasks_db.* TO tasks;"

sudo rm -rf /var/www/tasks
sudo mkdir /var/www/tasks
sudo chmod a+wrx /var/www/tasks/
cp web_server /var/www/tasks/ -r

if [ ! -d config_cache ]; then
  mkdir config_cache
fi
cd config_cache
composer require lcobucci/jwt lcobucci/Clock ramsey/uuid
cp ./composer.json /var/www/tasks/web_server/
cp ./composer.lock /var/www/tasks/web_server/
cp ./vendor /var/www/tasks/web_server/ -r
cd ..

# Generate secret used for jwt hashing
openssl rand -out /var/www/tasks/web_server/secret.key -base64 256
# Generate the certificate and secret used for https
openssl req -x509 -nodes -days 730 -newkey rsa:2048 -keyout /var/www/tasks/tasks.key -out /var/www/tasks/tasks.pem -config san.cnf

# Generate php config file
printf "<?php\n// This file is automatically generated\n\ndeclare(strict_types=1);\n\nclass Config\n{\n" | tee -a /var/www/tasks/web_server/config.php > /dev/null
printf "    public static string \$database_hostname = \"localhost\";\n" | tee -a /var/www/tasks/web_server/config.php > /dev/null
printf "    public static string \$database_username = \"tasks\";\n" | tee -a /var/www/tasks/web_server/config.php > /dev/null
printf "    public static string \$database_password = \"%s\";\n" "$db_pass" | tee -a /var/www/tasks/web_server/config.php > /dev/null
printf "    public static string \$database_name = \"tasks_db\";\n" | tee -a /var/www/tasks/web_server/config.php > /dev/null
printf "}\n" | tee -a /var/www/tasks/web_server/config.php > /dev/null

sudo rm -f /etc/nginx/sites-available/tasks
sudo cp ./nginx_config /etc/nginx/sites-available/tasks
sudo rm -f /etc/nginx/sites-enabled/tasks
sudo ln -s /etc/nginx/sites-available/tasks /etc/nginx/sites-enabled/tasks

sudo systemctl restart nginx php8.4-fpm

printf "Add the following lines to the end of \"/etc/mysql/mariadb.cnf\":\n[mysqld]\nevent_scheduler = on\n"
printf "\nIf you edited the file run \"sudo systemctl restart mariadb\" (or your init system's equivalent)\n"
